"""add logo_url to job_boards

Revision ID: a3ef6bab5077
Revises: e8d569ba049c
Create Date: 2025-11-24 16:26:25.203908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ef6bab5077'
down_revision: Union[str, Sequence[str], None] = 'e8d569ba049c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_boards', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_boards', 'logo_url')
    # ### end Alembic commands ###
